import { Task } from '@/types';

export const MOCK_TASKS: Task[] = [
  // Today's Scheduled Tasks (2026-05-25)
  {
    id: 'task-1',
    title: 'Design System & CSS Token Architecture',
    description: 'Review Tailwind v4 theme specifications, set up custom palette tokens, and design the component-level grid systems.',
    status: 'in_progress',
    priority: 'high',
    tags: ['Design', 'TailwindCSS v4', 'UI/UX'],
    project: 'Floris App',
    date: '2026-05-25',
    startTime: '09:00',
    endTime: '10:30',
    duration: 90,
    estimatedDuration: 90,
    completed: false,
    color: 'indigo',
    type: 'focus',
    createdAt: '2026-05-24T18:00:00Z',
    updatedAt: '2026-05-25T09:00:00Z',
  },
  {
    id: 'task-2',
    title: 'Floris Client Sprint Sync',
    description: 'Weekly alignment meeting with the engineering team to review dashboard progress, API integrations, and client feedback.',
    status: 'done',
    priority: 'high',
    tags: ['Meeting', 'Floris', 'Sprint'],
    project: 'Floris App',
    date: '2026-05-25',
    startTime: '11:00',
    endTime: '11:45',
    duration: 45,
    estimatedDuration: 45,
    completed: true,
    color: 'emerald',
    type: 'meeting',
    createdAt: '2026-05-24T10:00:00Z',
    updatedAt: '2026-05-25T11:45:00Z',
  },
  {
    id: 'task-3',
    title: 'Proposal Pitch & Email Triage',
    description: 'Respond to incoming client inquiries on Upwork and finalize the proposal document for the new PropTrader expansion project.',
    status: 'done',
    priority: 'medium',
    tags: ['Admin', 'Upwork', 'Proposal'],
    project: 'Personal Brand',
    date: '2026-05-25',
    startTime: '13:00',
    endTime: '13:45',
    duration: 45,
    estimatedDuration: 45,
    completed: true,
    color: 'amber',
    type: 'admin',
    createdAt: '2026-05-25T08:00:00Z',
    updatedAt: '2026-05-25T13:45:00Z',
  },
  {
    id: 'task-4',
    title: 'Refactor Dashboard Grid Flow & Jotai Atoms',
    description: 'Implement complex drag-and-drop mechanics in the timeline grid and set up global Jotai state atom synchronization.',
    status: 'blocked',
    priority: 'urgent',
    tags: ['Refactoring', 'Jotai', 'TypeScript'],
    project: 'Task Tracker SaaS',
    date: '2026-05-25',
    startTime: '14:00',
    endTime: '16:30',
    duration: 150,
    estimatedDuration: 180,
    completed: false,
    color: 'rose',
    type: 'deep_work',
    createdAt: '2026-05-24T12:00:00Z',
    updatedAt: '2026-05-25T14:30:00Z',
  },
  {
    id: 'task-5',
    title: 'Tailwind v4 PostCSS Build Integration',
    description: 'Upgrade the core build configuration to compile Tailwind CSS v4 directives inside CSS blocks and test for HMR stability.',
    status: 'not_started',
    priority: 'medium',
    tags: ['DevOps', 'Webpack', 'Tailwind'],
    project: 'Task Tracker SaaS',
    date: '2026-05-25',
    startTime: '17:00',
    endTime: '18:00',
    duration: 60,
    estimatedDuration: 60,
    completed: false,
    color: 'sky',
    type: 'focus',
    createdAt: '2026-05-25T07:00:00Z',
    updatedAt: '2026-05-25T07:00:00Z',
  },
  {
    id: 'task-6',
    title: 'Cardio & Strength Training Session',
    description: 'Full-body workout routine at the local gym, followed by a 15-minute mindfulness and mobility routine.',
    status: 'not_started',
    priority: 'low',
    tags: ['Fitness', 'Health'],
    project: 'Personal Development',
    date: '2026-05-25',
    startTime: '18:30',
    endTime: '19:45',
    duration: 75,
    estimatedDuration: 75,
    completed: false,
    color: 'violet',
    type: 'personal',
    createdAt: '2026-05-25T06:00:00Z',
    updatedAt: '2026-05-25T06:00:00Z',
  },

  // Today's Unscheduled Tasks (2026-05-25)
  {
    id: 'task-7',
    title: 'Update Upwork Portfolio Case Studies',
    description: 'Sanitize previous Next.js developer dashboard screenshots and write a detailed description of architectural modernizations.',
    status: 'not_started',
    priority: 'high',
    tags: ['Portfolio', 'Upwork', 'Marketing'],
    project: 'Personal Brand',
    date: '2026-05-25',
    estimatedDuration: 120,
    completed: false,
    color: 'indigo',
    type: 'outreach',
    createdAt: '2026-05-24T15:00:00Z',
    updatedAt: '2026-05-24T15:00:00Z',
  },
  {
    id: 'task-8',
    title: 'Draft Weekly Developer Operations Newsletter',
    description: 'Write about the benefits of combining kanban boards with vertical daily timeline calendars in personal work schedules.',
    status: 'not_started',
    priority: 'medium',
    tags: ['Newsletter', 'Writing'],
    project: 'Personal Brand',
    date: '2026-05-25',
    estimatedDuration: 60,
    completed: false,
    color: 'amber',
    type: 'admin',
    createdAt: '2026-05-25T09:00:00Z',
    updatedAt: '2026-05-25T09:00:00Z',
  },
  {
    id: 'task-9',
    title: 'Renew domain for tasktracker.dev',
    description: 'Ensure auto-renewal is active on Namecheap and update billing credentials in dashboard settings.',
    status: 'not_started',
    priority: 'urgent',
    tags: ['Billing', 'Infrastructure'],
    project: 'Task Tracker SaaS',
    date: '2026-05-25',
    estimatedDuration: 15,
    completed: false,
    color: 'rose',
    type: 'urgent',
    createdAt: '2026-05-25T09:30:00Z',
    updatedAt: '2026-05-25T09:30:00Z',
  },
  {
    id: 'task-10',
    title: 'Review pull request #402 for floris-api',
    description: 'Verify the NestJS database migration script and run local E2E test suites for analytics routes.',
    status: 'done',
    priority: 'low',
    tags: ['Review', 'NestJS', 'API'],
    project: 'Floris App',
    date: '2026-05-25',
    estimatedDuration: 40,
    completed: true,
    color: 'emerald',
    type: 'admin',
    createdAt: '2026-05-24T09:00:00Z',
    updatedAt: '2026-05-25T09:40:00Z',
  },

  // Neighboring Days (2026-05-24 and 2026-05-26)
  {
    id: 'task-11',
    title: 'Yesterday Retro & Goal Planning',
    description: 'Analyze last week\'s velocity and schedule the high-impact items for the coming sprint.',
    status: 'done',
    priority: 'medium',
    tags: ['Planning', 'Review'],
    project: 'Personal Development',
    date: '2026-05-24',
    startTime: '09:00',
    endTime: '10:00',
    duration: 60,
    estimatedDuration: 60,
    completed: true,
    color: 'emerald',
    type: 'admin',
    createdAt: '2026-05-23T15:00:00Z',
    updatedAt: '2026-05-24T10:00:00Z',
  },
  {
    id: 'task-12',
    title: 'Onboard New PropTrader UI Developer',
    description: 'Go over the Next.js project directory, explain the component splits, and review Git branching protocols.',
    status: 'not_started',
    priority: 'high',
    tags: ['Onboarding', 'Meeting'],
    project: 'Floris App',
    date: '2026-05-26',
    startTime: '10:00',
    endTime: '11:00',
    duration: 60,
    estimatedDuration: 60,
    completed: false,
    color: 'indigo',
    type: 'meeting',
    createdAt: '2026-05-25T08:00:00Z',
    updatedAt: '2026-05-25T08:00:00Z',
  }
];
